const knex = require("knex")(require("../knexfile"));
const axios = require('axios');
const qs = require('qs');
const { param } = require("../routes/genres");
require('dotenv').config();

const { URL_TOKEN, URL_API, CLIENT_ID, CLIENT_SECRET } = process.env;

//creating auth token to send in call to spotify API to get access token
const auth_token = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`, 'utf-8').toString('base64');

const headers = {
    headers: {
        "Accept": "*/*",
        'Authorization': `Basic ${auth_token}`,
        'Content-Type': 'application/x-www-form-urlencoded',
    }
}

const access_token = {};

const authHeader = {};

//function to retrieve the access token 
async function getToken(refresh_token) {
    let response;

    const data = qs.stringify({ 'grant_type': 'refresh_token', 'refresh_token': `${refresh_token}` });

    try {
        response = await axios.post(URL_TOKEN, data, headers)
    } catch (error) {
        console.log(`Error retrieving access token: ${error}`);
        return getToken();
    }
    access_token.token = response.data.access_token;
    access_token.timestamp = Date.now();
    //Construct header for API calls
    authHeader.headers = { 'Authorization': `Bearer ${access_token.token}` };
}

const generatePlaylist = async (req, res) => {
    const { params } = req.body;

    const users = await knex("users").where({ spotify_id: params.spotify_id });

    await getToken(users[0].refresh_token);

    delete params.spotify_id;

    const tracksList = [];

    const options = {
        params: params,
        headers: {
            'Authorization': `Bearer ${access_token.token}`
        }
    }

    try {
        const recomendations = await axios.get(`${URL_API}/recommendations`, options);
        const recomendationTracks = recomendations.data.tracks;
        for (i = 0; i < recomendationTracks.length; i++) {
            const newTrack = {};
            newTrack.name = recomendationTracks[i].name;
            newTrack.artist = recomendationTracks[i].artists[0].name;
            newTrack.uri = recomendationTracks[i].uri;
            if (recomendationTracks[i].album.images.length) {
                newTrack.artwork = recomendationTracks[i].album.images[0].url;
            }
            tracksList.push(newTrack);
        }
        return res.status(200).send(tracksList);
    } catch (error) {
        console.log(`Error retrieving recommendations playlist: ${error}`)
    }
}

const savePlaylist = async (req, res) => {
    const { params } = req.body;

    const users = await knex("users").where({ spotify_id: params.spotify_id });

    await getToken(users[0].refresh_token);

    const options = {
        method: 'POST',
        url: `${URL_API}/users/${params.spotify_id}/playlists`,
        headers: {
            Accept: '*/*',
            Authorization: `Bearer ${access_token.token}`,
            'Content-Type': 'application/json'
        },
        data: { name: `${params.name}`, description: "Inspiration playlist generated by Trax"  }
    };

    let newPlaylist;

    try {
        newPlaylist = await axios.request(options);
    } catch (error) {
        console.log(error.response.data);
        console.log(`Error creating playlist: ${error}`);
        return res.status(500).json(error);
    }

    const newPlaylistOptions = {
        method: 'POST',
        url: `${newPlaylist.data.href}/tracks`,
        headers: {
            Accept: '*/*',
            Authorization: `Bearer ${access_token.token}`,
            'Content-Type': 'application/json'
        },
        data: { uris: params.uris }
    };

    try {
        await axios.request(newPlaylistOptions);
        return res.status(201).json('Success!');
    } catch (error) {
        console.log(error.response.data);
        console.log(`Error adding songs to playlist: ${error}`);
        return res.status(500).json(error);
    }

}

module.exports = {
    generatePlaylist,
    savePlaylist
}